spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ordermanagement
    username: root
    password: admin123
server:
  port: 8080
  servlet:
    context-path: /api/v1

jwt:
  private-key: ""
  public-key: ""