spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ordermanagement
    username: root
    password: admin123
server:
  port: 8080
  servlet:
    context-path: /api/v1


jwt:
  secretKey: SeVUMdGZGhJffiJ3jrz4GM5tTl1ZIeFBnuQb8ePzho0ieJIOxqDL8tXIZJkj9+DAq55UAHzBfqpCOHfuIAHh8g==